name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: studio-offline-build-${{ github.sha }}
          path: |
            target/release/studio_offline.dll
            target/release/webview_who.dll
            target/release/studio_offline_server.exe
            server/*.exe
          if-no-files-found: error
